# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VegasCredentials < Formula
  desc "A helper utility that plugs into standard credential_process to assume AWS IAM Role with – Yubikey Touch and Authenticator App – TOTP MFA to provide session credentials – with automatic refreshing."
  homepage ""
  version "0.11.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.11.1/vegas-credentials_0.11.1_darwin_arm64.tar.gz"
      sha256 "1cbe562ac0ead598493aa78529a12eeeca667369c8c1f0210c433fdd45ee2fef"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.11.1/vegas-credentials_0.11.1_darwin_amd64.tar.gz"
      sha256 "0dd8de835ab21266eebfb14d3d245ed8ced8b4b4ebc7a05272005fd148adf437"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.11.1/vegas-credentials_0.11.1_linux_amd64.tar.gz"
      sha256 "ab1a1168512b5889afe29111fee4ac7dee072478446b7c779143dbd5d30d1d4b"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.11.1/vegas-credentials_0.11.1_linux_arm64.tar.gz"
      sha256 "bebe72c059c44a0a8bf7dc8e1b2039e183166cadb5ef632d922e5f67a586f169"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  depends_on "git"
end
