# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VegasCredentials < Formula
  desc "A helper utility that plugs into standard credential_process to assume AWS IAM Role with – Yubikey Touch and Authenticator App – TOTP MFA to provide session credentials – with automatic refreshing."
  homepage ""
  version "0.10.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.10.4/vegas-credentials_0.10.4_darwin_arm64.tar.gz"
      sha256 "d2e840c7d0ccebcc1d9ac27216da858066b663f54153d6af9788b13cc010a1a3"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.10.4/vegas-credentials_0.10.4_darwin_amd64.tar.gz"
      sha256 "af095cc9f26bf501be382c18a83dbf651b86c3ca583821de5afb74d7d0429994"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.10.4/vegas-credentials_0.10.4_linux_arm64.tar.gz"
      sha256 "3e2bfa60e05469bcadfb54f38aefcbd078504719a7a0380a87dc572cc8e2da27"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.10.4/vegas-credentials_0.10.4_linux_amd64.tar.gz"
      sha256 "8871bc600dc61605381768e168e91a761c7ae60357e8f765f16ef286a5dd4c13"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  depends_on "git"
end
