# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VegasCredentials < Formula
  desc "A helper utility that plugs into standard credential_process to assume AWS IAM Role with – Yubikey Touch and Authenticator App – TOTP MFA to provide session credentials – with automatic refreshing."
  homepage ""
  version "0.13.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.13.4/vegas-credentials_0.13.4_darwin_arm64.tar.gz"
      sha256 "94b6d7473833f0071da63f78db05375489d633772e5cc57b9f4ff5e06096a42e"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.13.4/vegas-credentials_0.13.4_darwin_amd64.tar.gz"
      sha256 "bbfe53f3ff00c0b88e94d91f5e26671c9e254dc6615b1f9b3099097660c097d2"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.13.4/vegas-credentials_0.13.4_linux_arm64.tar.gz"
      sha256 "88d009a0404a37393ec7a1ffd22e5bc6298ae3edb8315e513975add34cde2426"

      def install
        bin.install "vegas-credentials"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aripalo/vegas-credentials/releases/download/v0.13.4/vegas-credentials_0.13.4_linux_amd64.tar.gz"
      sha256 "790abbd3a43aea67612bcfba6ef1df9c08f08e0d93d8a25cfdb986dbfeeea13b"

      def install
        bin.install "vegas-credentials"
      end
    end
  end

  depends_on "git"
end
